[gcp]
type = "service_account"
project_id = "glassy-totality-425316-j3"
private_key_id = "2853a6ceb34eef0074250f286259695b3ec1eef2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCkKtPTmiSd4A2/
Rr8p6lkAnMgoIAx/p5FvNNQzCaTpxzaJBkr1zj4buYbeCHyaJtwUFumZ6W1UzaXl
NnlGcmFXHEgdiqQKIkYAbfOl/nDtymP+vN90we0r/3kEohdZOyALp1gcoNtd66SA
lEbLh3F6ylArWBpMLjGHa3BvHVzd47oFASvnXJb5FiOsGHXnzWEt6MuBdLxY0ahE
5rMpTHLKRmOjT4EoKsaganb/P9ty9d9vn/Eks/FsuA8qFShPodz36gIlX9Xwn83h
C+FlejyunxWKJO/YhfsSiKGHDiJaWQWOWhwAV9SaUIrjvrz/Y+hQQ0jeEsRIUm9N
/n7x6rOTAgMBAAECggEAFdQD+lzChaNm8IntnRsl3mj6TCuGvep/8fNqS6b6oIL2
g12s1eYoZ/NRNXCXcL+9/4XUZbyd5uq5JjMKCQ3oV3bRN+xZR2erOx9jiCy+wz9n
8FUYuSOX74O2iaErzZeI+UO0+YmB4YkVhGsyxpkpw5Pm+Pxr8rkpqMHmXz/eOzp3
lpp8Olt+eNlyoJjSSvhE0zmZM2YG/lcKayrj24N9FRPRsbJDcPp3Vxsqfo+d7y2y
WJt5KGEYe1hSteCx7b/D41JC8XZjsRasF6jxF0VSEZ87UPbG6CXLW2Ke+9ZEc4Tv
JWCxOblAthU7U5qe5OqgYduf/0V/vg7AzDwr3AQ5sQKBgQDiWoi+odTrBKrTTaRD
AsZ20LfwT2huKEeXdVDENY6pUCgKW8Vky6yBRpXbIkMMlxz6pNLknJmMmjqVx/wF
6/d7VcvF7ux7kSLAAqFkQG81G/2viCNkvbPBYh6qhT5Po8X6BykjbnYjEIyO304V
EHGDH4y0siXgHV8cPNkEikn5RwKBgQC5qztp5dMXDpFnOUcMTE249w94ZbegYOT/
abkZIIhcO6Jo3TE8/kBVKzjbvTJ/Gn30D1DYemfPGVOFTgVl4w6/UTToQimjmS0c
fUMKn3qCWF1y7ax37FMXhGgD3HcIxmXXlB9TkhpDRclZPRUZdq/2es3owQES1UUH
az/qY2UZVQKBgGC5eTek5dwr2WeEBQ5RkEdTd1ZsSF7SPY1+Jy5BCJ5XT1Tl1Fr3
Idb4N681W9t0c4CzkB76wC6x9RjuJUbOh6mfhv0k1M8UvPm55gd19U+Hj4dDsIQr
ADZB3ILXf0H+5Omrx6uJV1gyiS3ARJiBt0/l2nWYrtCvHGZvpfjnsyafAoGAJ6Au
7vv44Evgpnon+qzyTY6VA6oZ1aW4WfaTZZR25dBoah8DGjRdQJAX83XeqBfcV9FI
/Nqq+x05oRK0vjkGdbh8JTGxt1PCt/jX7RV6TQVU9GlbTMDoPvWoSWKtGPdW1vqq
8OgWqNLlFSGfNi8JgP5Wod1HQGC5+cpe+sQ52H0CgYBiRhgn+2FabhqRV/14+HAB
hzcMGGSHtNTkUnC/iWC3N47qE+qaTGmrdDa/I7EKjoFJFZx9v++J8O7jiml3uynp
VCxLfys13uPKHhgTg9e9NXMLi8KF0fd0DRvu6U0w/CnDPCxBKsxejHcEI783atAm
Im9gVbW6pGs12dY5HnWOJw==
-----END PRIVATE KEY-----"""
client_email = "sn-en-trans@glassy-totality-425316-j3.iam.gserviceaccount.com"
client_id = "109067957915491796483"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sn-en-trans%40glassy-totality-425316-j3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
